version: '2'
services:
  web_models:
    image: rspec-rails-examples
    working_dir: /app
    command: 'rspec spec/models'
    links:
      - postgresmodels
    environment:
      RAILS_ENV: 'test'
      DATABASE_URL: 'postgres://postgres:@postgresmodels:5432/rspec_test'
  postgresmodels:
    image: postgres
  web_controllers:
    image: rspec-rails-examples
    command: 'rspec spec/models'
    links:
      - postgrescontrollers
    environment:
      RAILS_ENV: 'test'
      DATABASE_URL: 'postgres://postgres:@postgrescontrollers:5432/rspec_test'
  postgrescontrollers:
    image: postgres
  web_tasks:
    image: rspec-rails-examples
    working_dir: /app
    command: 'rspec spec/tasks'
    links:
      - postgrescontrollers
    environment:
      RAILS_ENV: 'test'
      DATABASE_URL: 'postgres://postgres:@postgrescontrollers:5432/rspec_test'
  web_jobs:
    image: rspec-rails-examples
    working_dir: /app
    command: 'rspec spec/jobs'
    links:
      - postgresmodels
    environment:
      RAILS_ENV: 'test'
      DATABASE_URL: 'postgres://postgres:@postgresmodels:5432/rspec_test'
