version: '2'
services:
  web_models:
    image: rspec-rails-examples
    command: 'rspec spec/models'
    entrypoint: ''
    links:
      - postgres_models
    environment:
      RAILS_ENV: 'test'
      DATABASE_URL: 'postgres://postgres:@postgres_models:5432/rspec_test'
  postgres_models:
    image: postgres
  web_controllers:
    image: rspec-rails-examples
    command: 'rspec spec/models'
    entrypoint: ''
    links:
      - postgres_controllers
    environment:
      RAILS_ENV: 'test'
      DATABASE_URL: 'postgres://postgres:@postgres_controllers:5432/rspec_test'
  postgres_controllers:
    image: postgres
